### ISSUE TITLE
Magento 2.4.1-p1 compatibility

### ISSUE THREAD

**Issue by kamorana** [doofinder/doofinder-magento2-es-compat#13]
I am getting this error trying to update to Magento 2.4.1-p1 from 2.4.1

`- doofinder/doofinder-magento2-es-compat v3.0.7 requires magento/product-community-edition >= 2.3.2 <= 2.4.1 -> satisfiable by magento/product-community-edition[2.3.6-p1, 2.4.1, 2.3.6, 2.4.0-p1, 2.4.0, 2.3.5-p2, 2.3.4-p2, 2.3.5-p1, 2.3.5, 2.3.3-p1, 2.3.4, 2.3.2-p2, 2.3.3, 2.3.2] but these conflict with your requirements or minimum-stability.
`

**Comment by carlosescri** [comment]
It should be working. Sorry for the delay.
