### ISSUE TITLE
Mismatch between versions

### ISSUE THREAD

**Issue by BorisovskiP** [doofinder/doofinder-magento2-es-compat#5]
Hi, when updating Magento to 2.4.0 we get an error where `doofinder/doofinder-magento2-es-compat v3.0.1 requires magento/product-community-edition >= 2.3.2 <= 2.3.5-p1 `. Could you please update the requirements so we are able to update to the newer version of Magento?

**Comment by carlosescri** [comment]
Thanks for reporting. This should be fixed.
